= Authenticating with Azure

âœ link:readme.md[>> View scripts]

Before invoking any of the scripts, you will need to authenticate with Azure.

Open a terminal/command line and navigate to the root of the folder of the toolkit. 

Sign into the Azure CLI:

`az login`

This prompts you to log in using the Azure web interface. 

If your account is associated with more than one subscription, you'll then need to set the default subscription you want to target after you login:

`az account set --subscription {subscription GUID}`

You are now ready to invoke link:readme.md[the scripts].

////
[options="header",cols="<.< 35% a,<.< 5%,<.< 60%"]
|===
| Argument | Required? | Description

| [source]
----
--client-id
----
| Optional
| Specifies the ClientId. This value can be a SPN or AAD Object ID
// TODO: provide more detail

| [source]
----
--secret
----
| Optional
| Specifies the ClientId's secret
// TODO: provide more detail

| [source]
----
--tenant-id
----
| Optional
| Specifies the TenantId
// TODO: provide more detail

|===
 ////